cryptocollector_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('cryptos/', views.cryptos_index, name='index'),
    # path to see each crypto by it self
    path('cryptos/<int:crypto_id>/', views.cryptos_detail, name='detail'),
    # path to create a new crypto
    path('cryptos/create/', views.CryptoCreate.as_view(), name='cryptos_create'),
    # path to update crypto
    path('cryptos/<int:pk>/update/', views.CryptoUpdate.as_view(), name='cryptos_update'),
    # path to delete a crypto
    path('cryptos/<int:pk>/delete/', views.CryptoDelete.as_view(), name='cryptos_delete'),
    # path for adding the purchase 
    path('cryptos/<int:crypto_id>/add_purchase/', views.add_purchase, name='add_purchase'),

    # associate a feelings with a crypto (M:M)
    path('cryptos/<int:crypto_id>/assoc_feelings/<int:feeling_id>/', views.assoc_feeling, name='assoc_feeling'),

    # remove a feelings with a crypto (M:M)
    path('cryptos/<int:crypto_id>/remove_feeling/<int:feeling_id>/', views.remove_feeling, name='remove_feeling'),

    # path to add pictures
    path('cryptos/<int:crypto_id>/add_photo/', views.add_photo, name='add_photo'), 

    # feelings urls
    path('feelings/', views.feelings_index, name='all_feelings'),
    path('feelings/<int:feeling_id>/', views.feeling_detail, name='feeling_detail'),
    path('feelings/create/', views.Create_feeling.as_view(), name='create_feeling'),
    path('feelings/<int:pk>/update/', views.Update_feeling.as_view(), name='update_feeling'),
    path('feelings/<int:pk>/delete/', views.Delete_feeling.as_view(), name='delete_feeling'),

]

main_app/models.py
from django.db import models

# Import the reverse function
from django.urls import reverse

from datetime import date
# Import the User
from django.contrib.auth.models import User

class Feelings(models.Model):
    status = models.CharField(max_length=10)
    color = models.CharField(max_length=20)

    # Other goodness such as 'def __str__():' below
    def __str__(self):
        return f'{self.status} {self.color}'

    # Add this method
    def get_absolute_url(self):
        return reverse('feelings_detail', kwargs={'feelings_id': self.id})    

# Create your models here.
class Crypto(models.Model):
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    description = models.TextField(max_length=250)
    amount = models.IntegerField()

    # Add the M:M relationship
    feelings = models.ManyToManyField(Feelings)

    # Add the foreign key linking to a user instance
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detail', kwargs={'crypto_id': self.id})


# purchase model
class Purchase(models.Model):
    date = models.DateField('Purchase Date')
    purchase_price = models.IntegerField(default=0)
    total_amount = models.IntegerField(default=0)

    # Create a crypto_id FK
    crypto = models.ForeignKey(Crypto, on_delete=models.CASCADE)

    def __str__(self):
        # Nice method for obtaining the friendly value of a Field.choice
        return f"{self.get_purchase_display()} on {self.date}"

    # change the default sort
    class Meta:
        ordering = ['-date']

# photo model
class Photo(models.Model):
    url = models.CharField(max_length=200)
    crypto = models.ForeignKey(Crypto, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for crypto_id: {self.crypto_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Purchase

class PurchaseForm(ModelForm):
    class Meta:
        model = Purchase
        fields = ['date', 'purchase_price', 'total_amount']

main_app/views.py
from django.shortcuts import render, redirect

from django.http import HttpResponse

# import class-based-views
from django.views.generic.edit import CreateView, UpdateView, DeleteView
# import models
from .models import Crypto, Feelings, Photo
from .forms import PurchaseForm

# imports for image upload
import uuid
import boto3


# s3 variables
S3_BASE_URL = 'https://s3.us-east-1.amazonaws.com/'
BUCKET = 'crypto-collector'
# Create your views here.

# Define the home view
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def cryptos_index(request):
    cryptos = Crypto.objects.all()
    return render(request, 'cryptos/index.html', { 'cryptos': cryptos })

def cryptos_detail(request, crypto_id):
    crypto = Crypto.objects.get(id=crypto_id)

    # Get the feelings for crypto doesn't have
    feelings_crypto_doesnt_have = Feelings.objects.exclude(id__in = crypto.feelings.all().values_list('id'))

    # instantiate FeedingForm to be rendered in the template
    purchase_form = PurchaseForm()
    return render(request, 'cryptos/detail.html', { 
        'crypto': crypto, 
        'purchase_form':purchase_form,
        # Add the feelings to be displayed
        'feelings': feelings_crypto_doesnt_have
        })

def add_purchase(request, crypto_id):
    # create the ModelForm using the data in request.POST
    form = PurchaseForm(request.POST)
    # validate the form
    if form.is_valid():
        # don't save the form to the db until it
        # has the crypto_id assigned
        new_purchase = form.save(commit=False)
        new_purchase.crypto_id = crypto_id
        new_purchase.save()
    return redirect('detail', crypto_id=crypto_id)

class CryptoCreate(CreateView):
    model = Crypto
    fields = '__all__'

class CryptoUpdate(UpdateView):
    model = Crypto
    fields = ['price', 'description', 'amount']

class CryptoDelete(DeleteView):
    model = Crypto
    success_url = '/cryptos/'

# Feelings views
def feelings_index(request):
    feelings = Feelings.objects.all()
    context = {'feelings': feelings}
    
    return render(request, 'feeling/index.html', context)


def feeling_detail(request, feeling_id):
    feeling = Feelings.objects.get(id=feeling_id)
    context = {
        'feeling': feeling
    }
    return render(request, 'feeling/detail.html', context)
    
class Create_feeling(CreateView):
    model = Feelings
    fields = '__all__'


class Update_feeling(UpdateView):
    model = Feelings
    fields = ['color']

class Delete_feeling(DeleteView):
    model = Feelings
    success_url = '/feelings/' 

def assoc_feeling(request, crypto_id, feeling_id):
    # Note that you can pass a feeling's id instead of the whole object
    Crypto.objects.get(id=crypto_id).feelings.add(feeling_id)
    return redirect('detail', crypto_id=crypto_id)

def remove_feeling(request, crypto_id, feeling_id):
    # Note that you can pass a feeling's id instead of the whole object
    Crypto.objects.get(id=crypto_id).feelings.remove(feeling_id)
    return redirect('detail', crypto_id=crypto_id)

def add_photo(request, crypto_id):
    # photo-file will be the "name" attribute on the <input type="file">
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        # need a unique "key" for S3 / needs image file extension too
        key = uuid.uuid4().hex[:6] + photo_file.name[photo_file.name.rfind('.'):]
        # just in case something goes wrong
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            # build the full url string
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            # we can assign to crypto_id or crypto (if you have a crypto object)
            photo = Photo(url=url, crypto_id=crypto_id)
            photo.save()
        except:
            print('An error occurred uploading file to S3')
    return redirect('detail', crypto_id=crypto_id)

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<h1>About the Crypto Collector</h1>
<hr />
<p>Hire the Crypto Collector!</p>

{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Crypto Collector</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>

<body>
    <header class="navbar-fixed">
        <nav class="black">
            <div class="nav-wrapper">
                <ul>
                    <li><a href="/" class="left brand-logo">&nbsp;&nbsp;CryptoCollector</a></li>
                </ul>
                <ul class="right">
                    <li><a href="{% url 'about' %}">About</a></li>
                    <li><a href="{% url 'cryptos_create' %}">Add a Crypto</a></li>
                    <li><a href="{% url 'index' %}">View All My Cryptos</a></li>
                </ul>
            </div>
        </nav>
    </header>
    <main class="container">
        {% block content %}
        {% endblock %}
    </main>
    <footer class="page-footer black">
        <div class="right">All Rights Reserved, &copy; 2021 Crypto Collector &nbsp;</div>
    </footer>
</body>

</html>

main_app/templates/cryptos/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Crypto Details</h1>

<div class="row">
    <div class="col s6">
        <div class="card">
            <div class="card-content">
                <span class="card-title">{{ crypto.name }}</span>
                <p>Price: {{ crypto.price }}</p>
                <p>Description: {{ crypto.description }}</p>
                <p>Amount: {{ crypto.amount }}</p>
            </div>
            <div class="card-action">
                <a href="{% url 'cryptos_update' crypto.id %}">Edit</a>
                <a href="{% url 'cryptos_delete' crypto.id %}">Delete</a>
            </div>
        </div>

        {% for photo in crypto.photo_set.all %}
        <img class="responsive-img card-panel" src="{{photo.url}}">
        {% empty %}
        <div class="card-panel teal-text center-align">No Photos Uploaded</div>
        {% endfor %}

        <form action="{% url 'add_photo' crypto.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
            {% csrf_token %}
            <input type="file" name="photo-file">
            <br><br>
            <input type="submit" class="btn" value="Upload Photo">
        </form>

    </div>
    <div class="col s6">
        <form action="{% url 'add_purchase' crypto.id %}" method="post">
            {% csrf_token %}
            {{ purchase_form.as_p }}
            <input type="submit" class="btn" value="Add Purchase">
        </form>
        <table class="striped">
            <thead>
                <tr>
                    <th>Date</th>
                    <th>Purchase Price</th>
                    <th>Total Amount</th>
                </tr>
            </thead>
            <tbody>
                {% for purchase in crypto.purchase_set.all %}
                <tr>
                    <td>{{purchase.date}}</td>
                    <td>{{purchase.purchase_price}}</td>
                    <td>{{purchase.total_amount}}</td>
                    <td>{{purchase.get_purchase_display}}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>



<!-- This is all new markup to be added just above the <script> tag -->
<hr>
<div class="row">
    <div class="col s6">
        <h3>Your {{ crypto.name }} Feelings</h3>
        {% if crypto.feelings.count %}
        {% for feeling in crypto.feelings.all %}
        <div class="card">
            <div class="card-content">
                <span class="card-title">
                    <span style="color: {{ feeling.color }}">{{ feeling.status }}</span>
                </span>
            </div>
            <div class="card-action">
                <form action="{% url 'remove_feeling' crypto.id feeling.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn red">Remove</button>
                </form>
            </div>
        </div>

        {% endfor %}
        {% else %}
        <h5>No feelings :(</h5>{% endif %}
    </div>
    <!-- Available feelings will come after this line -->
    <div class="col s6">
        <h3>Available Feelings for {{crypto.name}} </h3>
        {% if feelings.count %}
        {% for feeling in feelings.all %}
        <div class="card">
            <div class="card-content">
                <span class="card-title">
                    <span style="color: {{ feeling.color }}">{{ feeling.status }}</span>
                </span>
            </div>
            <div class="card-action">
                <form action="{% url 'assoc_feeling' crypto.id feeling.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn">Add</button>
                </form>
            </div>
        </div>
        {% endfor %}
        {% else %}
        <h5>{{crypto.name}} Already Has All feelings Available</h5>
        {% endif %}

    </div>

    <script>
        var dateEl = document.getElementById('id_date');
        M.Datepicker.init(dateEl, {
            format: 'yyyy-mm-dd',
            defaultDate: new Date(),
            setDefaultDate: true,
            autoClose: true
        });
    </script>

    {% endblock %}

main_app/templates/cryptos/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Crypto List</h1>

{% for crypto in cryptos %}
<div class="card">
    <a href="{% url 'detail' crypto.id %}">
        <div class="card-content">
            <span class="card-title">{{ crypto.name }}</span>
            <p>Price: {{ crypto.price }}</p>
            <p>Description: {{ crypto.description }}</p>
            <p>Amount: {{ crypto.amount }}</p>
        </div>
    </a>
</div>
{% endfor %}

{% endblock %}

main_app/templates/feeling/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Feeling Details</h1>

<div class="card">
    <div class="card-content">
        <span class="card-title">{{ feeling.status }}</span>
        <p>color: {{ feeling.color }}</p>
    </div>
    <div class="card-action">
        <a href="{% url 'update_feeling' feeling.id %}">Edit</a>
        <a href="{% url 'delete_feeling' feeling.id %}">Delete</a>
    </div>
</div>

{% endblock %}

main_app/templates/feeling/index.html
{% extends 'base.html' %}
{% block content %}

{% for feeling in feelings %}

<div class="card">
    <a href="{% url 'feeling_detail' feeling.id %}">
        <div class="card-content">
            <span class="card-title">{{ feeling.status }}</span>
            <p>Color: {{ feeling.color }}</p>
        </div>
    </a>
</div>
{% comment %}
if there is no elements in our list will display no feelings
{% endcomment %}
{% empty %}

<div class="card">
    <div class="card-content">
        <span class="card-title">No feelings</span>
    </div>
</div>

{% endfor %}

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Home</h1>

{% endblock %}

main_app/templates/main_app/crypto_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<h1>Delete Crypto</h1>

<h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' crypto.id %}">Cancel</a>
</form>
{% endblock %}

main_app/templates/main_app/crypto_form.html
{% extends 'base.html' %}

{% block content %}
{% if object %}
<h1>Edit <span class="teal-text">{{object.name}}</span></h1>
{% else %}
<h1>Add Crypto</h1>
{% endif %}
<!-- Leaving the action empty makes the form post to the same url used to display it -->
<form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
        <!-- Render the inputs inside of <tr>s & <td>s -->
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
</form>
{% endblock %}